# Archivo: src/main/resources/application-staging.properties
spring.profiles.active=staging
server.port=8080

# Se inyectan desde variables de entorno en el servidor / docker-compose .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
