# Archivo: src/main/resources/application-production.properties
spring.profiles.active=production
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
